package com.lackatree.LackATree.enums;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Country {
    AFGHANISTAN("Afghanistan"),
    ANGOLA("Angola"),
    ALBANIA("Albania"),
    UNITED_ARAB_EMIRATES("United Arab Emirates"),
    ARGENTINA("Argentina"),
    ARMENIA("Armenia"),
    FRENCH_SOUTHERN_TERRITORIES("French Southern Territories"),
    AUSTRALIA("Australia"),
    AUSTRIA("Austria"),
    AZERBAIJAN("Azerbaijan"),
    BURUNDI("Burundi"),
    BELGIUM("Belgium"),
    BENIN("Benin"),
    BURKINA_FASO("Burkina Faso"),
    BANGLADESH("Bangladesh"),
    BULGARIA("Bulgaria"),
    BAHAMAS("Bahamas"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina"),
    BELARUS("Belarus"),
    BELIZE("Belize"),
    BOLIVIA("Bolivia"),
    BRAZIL("Brazil"),
    BRUNEI("Brunei"),
    BHUTAN("Bhutan"),
    BOTSWANA("Botswana"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic"),
    CANADA("Canada"),
    SWITZERLAND("Switzerland"),
    CHILE("Chile"),
    CHINA("China"),
    COTE_DIVOIRE("Cote d'Ivoire"),
    CAMEROON("Cameroon"),
    DEMOCRATIC_REPUBLIC_OF_CONGO("Democratic Republic of Congo"),
    CONGO("Congo"),
    COLOMBIA("Colombia"),
    COSTA_RICA("Costa Rica"),
    CUBA("Cuba"),
    CYPRUS("Cyprus"),
    CZECHIA("Czechia"),
    GERMANY("Germany"),
    DJIBOUTI("Djibouti"),
    DENMARK("Denmark"),
    GREENLAND("Greenland"),
    DOMINICAN_REPUBLIC("Dominican Republic"),
    ALGERIA("Algeria"),
    ECUADOR("Ecuador"),
    EGYPT("Egypt"),
    ERITREA("Eritrea"),
    SPAIN("Spain"),
    ESTONIA("Estonia"),
    ETHIOPIA("Ethiopia"),
    FINLAND("Finland"),
    FIJI("Fiji"),
    FRANCE("France"),
    FRENCH_GUIANA("French Guiana"),
    GABON("Gabon"),
    UNITED_KINGDOM("United Kingdom"),
    GEORGIA("Georgia"),
    GHANA("Ghana"),
    GUINEA("Guinea"),
    GAMBIA("Gambia"),
    GUINEA_BISSAU("Guinea-Bissau"),
    EQUATORIAL_GUINEA("Equatorial Guinea"),
    GREECE("Greece"),
    GUATEMALA("Guatemala"),
    GUYANA("Guyana"),
    HONDURAS("Honduras"),
    CROATIA("Croatia"),
    HAITI("Haiti"),
    HUNGARY("Hungary"),
    INDONESIA("Indonesia"),
    INDIA("India"),
    IRELAND("Ireland"),
    IRAN("Iran"),
    IRAQ("Iraq"),
    ICELAND("Iceland"),
    ISRAEL("Israel"),
    ITALY("Italy"),
    JAMAICA("Jamaica"),
    JORDAN("Jordan"),
    JAPAN("Japan"),
    KAZAKHSTAN("Kazakhstan"),
    KENYA("Kenya"),
    KYRGYZSTAN("Kyrgyzstan"),
    CAMBODIA("Cambodia"),
    SOUTH_KOREA("South Korea"),
    KOSOVO("Kosovo"),
    KUWAIT("Kuwait"),
    LAOS("Laos"),
    LEBANON("Lebanon"),
    LIBERIA("Liberia"),
    LIBYA("Libya"),
    SRI_LANKA("Sri Lanka"),
    LESOTHO("Lesotho"),
    LITHUANIA("Lithuania"),
    LUXEMBOURG("Luxembourg"),
    LATVIA("Latvia"),
    MOROCCO("Morocco"),
    MOLDOVA("Moldova"),
    MADAGASCAR("Madagascar"),
    MEXICO("Mexico"),
    NORTH_MACEDONIA("North Macedonia"),
    MALI("Mali"),
    MYANMAR("Myanmar"),
    MONTENEGRO("Montenegro"),
    MONGOLIA("Mongolia"),
    MOZAMBIQUE("Mozambique"),
    MAURITANIA("Mauritania"),
    MALAWI("Malawi"),
    MALAYSIA("Malaysia"),
    NAMIBIA("Namibia"),
    NEW_CALEDONIA("New Caledonia"),
    NIGER("Niger"),
    NIGERIA("Nigeria"),
    NICARAGUA("Nicaragua"),
    NETHERLANDS("Netherlands"),
    NORWAY("Norway"),
    NEPAL("Nepal"),
    NEW_ZEALAND("New Zealand"),
    OMAN("Oman"),
    PAKISTAN("Pakistan"),
    PANAMA("Panama"),
    PERU("Peru"),
    PHILIPPINES("Philippines"),
    PAPUA_NEW_GUINEA("Papua New Guinea"),
    POLAND("Poland"),
    PUERTO_RICO("Puerto Rico"),
    NORTH_KOREA("North Korea"),
    PORTUGAL("Portugal"),
    PARAGUAY("Paraguay"),
    QATAR("Qatar"),
    ROMANIA("Romania"),
    RUSSIA("Russia"),
    RWANDA("Rwanda"),
    WESTERN_SAHARA("Western Sahara"),
    SAUDI_ARABIA("Saudi Arabia"),
    SUDAN("Sudan"),
    SOUTH_SUDAN("South Sudan"),
    SENEGAL("Senegal"),
    SOLOMON_ISLANDS("Solomon Islands"),
    SIERRA_LEONE("Sierra Leone"),
    EL_SALVADOR("El Salvador"),
    SOMALIA("Somalia"),
    SERBIA("Serbia"),
    SURINAME("Suriname"),
    SLOVAKIA("Slovakia"),
    SLOVENIA("Slovenia"),
    SWEDEN("Sweden"),
    ESWATINI("Eswatini"),
    SYRIA("Syria"),
    CHAD("Chad"),
    TOGO("Togo"),
    THAILAND("Thailand"),
    TAJIKISTAN("Tajikistan"),
    TURKMENISTAN("Turkmenistan"),
    TIMOR("Timor"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago"),
    TUNISIA("Tunisia"),
    TURKEY("Turkey"),
    TAIWAN("Taiwan"),
    TANZANIA("Tanzania"),
    UGANDA("Uganda"),
    UKRAINE("Ukraine"),
    URUGUAY("Uruguay"),
    UNITED_STATES("United States"),
    UZBEKISTAN("Uzbekistan"),
    VENEZUELA("Venezuela"),
    VIETNAM("Vietnam"),
    VANUATU("Vanuatu"),
    WEST_BANK("West Bank"),
    YEMEN("Yemen"),
    SOUTH_AFRICA("South Africa"),
    ZAMBIA("Zambia"),
    ZIMBABWE("Zimbabwe"),
    CAPE_VERDE("Cape Verde"),
    COMOROS("Comoros"),
    MAURITIUS("Mauritius"),
    SEYCHELLES("Seychelles"),
    BAHRAIN("Bahrain"),
    MALDIVES("Maldives"),
    MARSHALL_ISLANDS("Marshall Islands"),
    MICRONESIA("Micronesia (country)"),
    NAURU("Nauru"),
    PALAU("Palau"),
    SAMOA("Samoa"),
    SINGAPORE("Singapore"),
    TONGA("Tonga"),
    TUVALU("Tuvalu"),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda"),
    BARBADOS("Barbados"),
    DOMINICA("Dominica"),
    GRENADA("Grenada"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis"),
    SAINT_LUCIA("Saint Lucia"),
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines"),
    ANDORRA("Andorra"),
    LIECHTENSTEIN("Liechtenstein"),
    MALTA("Malta"),
    MONACO("Monaco"),
    SAN_MARINO("San Marino"),
    KIRIBATI("Kiribati"),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe");

    private final String countryName;

    Country(String countryName) {
        this.countryName = countryName;
    }

    @JsonValue
    public String getStateName() {
        return countryName;
    }


    public static Country fromValue(String value) {
        for (Country status : Country.values()) {
            if (status.getStateName().equalsIgnoreCase(value)) {
                return status;
            }
        }

        return null;
    }
}
